sudo: required

language: node_js

node_js:
  - "5"

env:
  - CXX=g++-4.8

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libicns

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - ruby-dev

script:
- gem install fpm
- npm run dist
