version: 0.1.{build}

platform:
  - x64

install:
  - ps: Install-Product node 5 x64
  - npm install

build_script:
  - npm run dist

artifacts:
  - path: 'dist\win-x64\**\*.exe'
  - path: '**\*.nupkg'

deploy:
  provider: GitHub
  auth_token:
    secure: jCppa1myevxFxrEHErHpzqobQRAvqnW5c90ukBAC2qBuXDGiQHxxbF3DiM+9eWNN
  on:
    appveyor_repo_tag: true

test: off
